=== GuiForget/gradle-resolution-rules/src/test/resources/valid-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Resolution Rule",
  "description": "validation of resolution rules",
  "type": "object",
  "properties": {
    "align": {
      "type": "array"
    },
    "deny": {
      "type": "array"
    },
    "exclude": {
      "type": "array"
    },
    "reject": {
      "type": "array"
    },
    "replace": {
      "type": "array"
    },
    "substitute": {
      "type": "array"
    }
  },
  "required": [
    "align",
    "deny",
    "exclude",
    "reject",
    "replace",
    "substitute"
  ]
}

=== GuiForget/gradle-resolution-rules/src/main/resources/align-log4j2.json
{
    "align": [
            {
                "name": "align-log4j2",
                "group": "org.apache.logging.log4j",
                "includes": [],
                "excludes": ["slf4j-impl", "log4j12-api"],
                "reason": "Align Log4J 2 libraries",
                "author": "Danny Thomas <dannyt@netflix.com>",
                "date": "2016-09-29"
            }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== GuiForget/gradle-resolution-rules/src/main/resources/align-jersey.json
{
    "align": [
        {
            "name": "jersey-align",
            "group": "(com\\.sun\\.jersey|com\\.sun\\.jersey\\.contribs|com\\.sun\\.jersey\\.jersey-test-framework)",
            "excludes": ["jersey", "jersey-(jrebel|tests|spring|contribs)", "maven-wadl-plugin"],
            "reason": "Misaligned Jersey jars cause strange runtime errors.",
            "author": "noel.yap+github.com@gmail.com",
            "date": "2016-05-03"
        }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== GuiForget/gradle-resolution-rules/src/main/resources/replace-servlet.json
{
    "replace" : [
            {
                "module" : "javax.servlet:servlet-api",
                "with" : "javax.servlet:javax.servlet-api",
                "reason" : "servlet-api has been replaced with javax.servlet-api",
                "author" : "Rob Spieldenner",
                "date" : "2016-06-09T17:12:34.000Z"
            },
            {
              "module" : "javax.servlet:jsp-api",
              "with" : "javax.servlet.jsp:javax.servlet.jsp-api",
              "reason" : "jsp-api has been replaced with javax.servlet.jsp-api",
              "author" : "Rob Spieldenner",
              "date" : "2016-06-09T17:12:34.000Z"
            },
            {
                "module" : "javax.servlet.jsp:jsp-api",
                "with" : "javax.servlet.jsp:javax.servlet.jsp-api",
                "reason" : "jsp-api has been replaced with javax.servlet.jsp-api",
                "author" : "Rob Spieldenner",
                "date" : "2016-06-09T17:12:34.000Z"
            },
            {
                "module" : "javax.el:el-api",
                "with" : "javax.el:javax.el-api",
                "reason" : "el-api has been replaced with javax.el-api",
                "author" : "Rob Spieldenner",
                "date" : "2016-06-09T17:12:34.000Z"
            }
    ],
    "align": [],
    "substitute": [],
    "deny": [],
  "exclude": [],
    "reject": []
}

=== GuiForget/gradle-resolution-rules/src/main/resources/replace-guava.json
{
    "replace" : [
            {
                "module" : "com.google.guava:guava-jdk5",
                "with" : "com.google.guava:guava",
                "reason" : "Guava JDK5 can be safely replaced by Guava",
                "author" : "Steve Hill",
                "date" : "2016-12-05T00:00:00.000Z"
            }
    ],
    "align": [],
    "substitute": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== GuiForget/gradle-resolution-rules/src/main/resources/deny-genie-3.2.3.json
{
    "replace" : [],
    "substitute": [],
    "deny": [
        {
            "module": "com.netflix.genie:genie-core:3.2.3",
            "reason" : "Genie 3.2.3 is a retired build and should not be used",
            "author" : "Marco Primi <mprimi@netflix.com>",
            "date" : "2017-11-03T00:00:00.000Z"
        }
    ],
    "reject": [],
    "exclude": [],
    "align": []
}

=== GuiForget/gradle-resolution-rules/src/main/resources/align-eureka-client.json
{
    "align": [
        {
            "name": "align-eureka-client",
            "group": "com.netflix.eureka",
            "includes": ["eureka-(client|client-archaius2|client-jersey2|test-utils)"],
            "reason": "Align Eureka Client libraries.",
            "author": "David Liu <dliu@netflix.com>",
            "date": "2016-10-11"
        }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== GuiForget/gradle-resolution-rules/src/main/resources/align-xstream.json
{
    "align": [
            {
                "group": "com.thoughtworks.xstream",
                "match": "EXCLUDE_SUFFIXES",
                "reason": "Align all xstream libraries",
                "author": "Danny Thomas <dannyt@netflix.com>",
                "date": "2016-05-15"
            }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "exclude": [],
    "reject": []
}
